spring:
  datasource:
    url: jdbc:mysql://124.156.172.108:3306/jpa?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: root
    password: 123456
  jpa:
    hibernate:
#   更新或者创建数据表结构
      ddl-auto: update
#   控制台显示SQL
    show-sql: true
